#!/usr/bin/env bash
# No-agent cron entrypoint: bounty loop + deterministic lab notebook (no LLM/OAuth).
set -euo pipefail

REPO="${NSS_REPO:-/home/kt/projects/rtp/night-shift-security}"
cd "$REPO"

if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

git pull --ff-only 2>/dev/null || true

echo "NSS bounty-loop cron start $(date -Iseconds)"
hermes/scripts/nss-bounty-loop.sh --iterations 1 --refresh-scan

.venv/bin/python - <<'PY'
import json
from datetime import datetime, timezone
from pathlib import Path

repo = Path(".")
state_path = repo / "data/security_results/loop/state.json"
state = json.loads(state_path.read_text()) if state_path.is_file() else {}
runs = state.get("runs") or []
last = runs[-1] if runs else {}
slug = last.get("slug", "unknown")
date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
nb_dir = repo / "data/security_results/lab_notebook"
nb_dir.mkdir(parents=True, exist_ok=True)
path = nb_dir / f"{date}-bounty-loop-{slug}.md"
body = f"""# Lab entry — bounty-loop cron ({slug})

## Trigger
cron: nss-bounty-loop (no-agent script)

## Run
- slug: {slug}
- platform: {last.get('platform', '')}
- findings: {last.get('findings', '')}
- fork_reproduced: {last.get('fork_reproduced', '')}
- best_recommendation: {last.get('best_recommendation', '')}
- saturated_slugs: {', '.join(state.get('saturated_slugs') or [])}
- human_gate_pending: {state.get('human_gate_pending', False)}

## Notes
Auto-generated by nss-bounty-loop-cron.sh (SPEC v3.0.8). No submit_ready without human gate.
"""
path.write_text(body)
print(f"LAB_NOTEBOOK:{path}")
PY

echo "NSS bounty-loop cron ok $(date -Iseconds)"