[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 20000
evm_version = "cancun"
remappings = [
    "lib/openzeppelin-contracts/contracts/=src/variational/lib/openzeppelin-contracts/contracts/",
]

[fmt]
line_length = 100
